// Api
module.exports = {
  App: require('./src/App').default,
  Clipboard: require('./src/Clipboard').default,
  Edge: require('./src/Edge').default,
  FONT_AWESOME: require('./src/config/FONT_AWESOME').default,
  Graph: require('./src/Graph').default,
  Group: require('./src/Group').default,
  IIP: require('./src/Iip').default,
  Menu: require('./src/Menu').default,
  ModalBG: require('./src/ModalBG').default,
  Node: require('./src/Node').default,
  NodeMenu: require('./src/NodeMenu').default,
  NodeMenuPort: require('./src/NodeMenuPort').default,
  NodeMenuPorts: require('./src/NodeMenuPorts').default,
  Port: require('./src/Port').default,
  SVGImage: require('./src/common/SVGImage').default,
  TextBG: require('./src/common/TextBG').default,
  Tooltip: require('./src/Tooltip').default,
  arcs: require('./src/factories/menu/arcs').default,
  config: require('./src/config').default,
  contextPortSize: 36,
  factories: require('./src/factories').default,
  findAreaFit: require('./src/utils/findAreaFit').default,
  findMinMax: require('./src/utils/findMinMax').default,
  findNodeFit: require('./src/utils/findNodeFit').default,
  mixins: require('./src/mixins').default,
  fromJSON: require('./src/utils/fromJSON').default,
  renderDOM: require('react-dom').render,
  unmount: require('react-dom').unmountComponentAtNode,
  createElement: require('react').createElement
  /*
   nodeRadius: 8,
   nodeSide: 56,
   nodeSize: 72,
   zbpBig: 1.2,
   zbpNormal: 0.4,
   zbpSmall: 0.01
   */
}
